# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tires',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('model', models.CharField(max_length=200)),
                ('brand', models.CharField(choices=[(b'FIRE', b'Firestone'), (b'BRIDGE', b'Bridgestone'), (b'TRELL', b'Trelleborg'), (b'TITAN', b'Titan')], max_length=6)),
                ('country', models.CharField(max_length=30)),
                ('tech', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=100)),
                ('class_tire', models.CharField(choices=[(b'AGRI', b'\xd0\xa1\xd0\xb5\xd0\xbb\xd1\x8c\xd1\x85\xd0\xbe\xd0\xb7 \xd1\x88\xd0\xb8\xd0\xbd\xd0\xb0'), (b'TRUCK', b'\xd0\x93\xd1\x80\xd1\x83\xd0\xb7\xd0\xbe\xd0\xb2\xd0\xb0\xd1\x8f \xd1\x88\xd0\xb8\xd0\xbd\xd0\xb0'), (b'IND', b'\xd0\x98\xd0\xbd\xd0\xb4\xd1\x83\xd1\x81\xd1\x82\xd1\x80\xd0\xb8\xd0\xb0\xd0\xbb\xd1\x8c\xd0\xbd\xd0\xb0\xd1\x8f \xd1\x88\xd0\xb8\xd0\xbd\xd0\xb0')], max_length=6)),
                ('active', models.BooleanField(default=True)),
                ('arch', models.CharField(choices=[(b'BIAS', b'\xd0\x94\xd0\xb8\xd0\xb0\xd0\xb3\xd0\xbe\xd0\xbd\xd0\xb0\xd0\xbb\xd1\x8c\xd0\xbd\xd0\xb0\xd1\x8f'), (b'RADIAL', b'\xd0\xa0\xd0\xb0\xd0\xb4\xd0\xb8\xd0\xb0\xd0\xbb\xd1\x8c\xd0\xbd\xd0\xb0\xd1\x8f')], max_length=6)),
                ('sort', models.IntegerField(default=0)),
                ('pub_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
