# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0002_auto_20160317_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tires',
            name='arch',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tires',
            name='brand',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tires',
            name='class_tire',
            field=models.CharField(max_length=100),
        ),
    ]
