# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0003_auto_20160317_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='tires',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
    ]
