# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0004_tires_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tires',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
