# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0005_auto_20160318_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='tires',
            name='fullName',
            field=models.CharField(max_length=20, default="nullTire"),
        ),
    ]
